### PR TITLE
Added admin interface

### PR DESCRIPTION
**Pull request by afuhrtrumpet**
Completes #11

### CODE REVIEW

**Comment by mrogman** [comment]
Is there a way to login to the admin UI yet? When I go to /admin I get a message that says I need to be an admin to view the page but there's no way to login that I can see.

**Comment by mrogman** [comment]
Nevermind, we're going to have to use [meteor-roles](https://github.com/alanning/meteor-roles/) to attach permissions to users, which should probably be a separate issue. The code for this PR looks good to me, though.

**Comment by afuhrtrumpet** [comment]
I was trying to make a login page, but for some reason everything was cut
off (I think the existing CSS or scrollify?). I think what I ended up doing
was temporarily adding login buttons to the navbar. I wonder if there's a
way to add this to the /admin route...

**Comment by mrogman** [comment]
I don't see any login buttons or evidence of a login page. I did see that you were routing a login template to /login but the template doesn't exist. Is the code missing or just hasn't been written yet?

Also, what do you mean by adding 'this' to the /admin route?

**Comment by afuhrtrumpet** [comment]
Login buttons are up on the main page right now. For some reason this is breaking scrollify for me though.

I was wondering if there was a way to add the login buttons to the "You need to be an admin" page that shows up when you're not logged in. I'm not sure that's necessary though, as we could include an admin link on the navbar that only shows up when you're logged in as an admin.

**Comment by mrogman** [comment]
Cool, I see it. It is doing something weird to scrollify for me too, but this was also happening without the login button. If I resize the window a little bit, it starts working again for some reason...

I personally like the idea of just having a link to the admin interface that appears after signing in but I suppose it's just a matter of preference.

**Comment by afuhrtrumpet** [comment]
Admin link shows up on the navbar now if the user logged in is admin. Now I think the only thing we need is to fix scrollify (works the same for me, where it doesn't work until the screen size changes).

**Comment by afuhrtrumpet** [comment]
It's definitely the `<template name="main">` wrapping that's causing the scrollify weirdness. Might be out of our control without modifying scrollify.

**Comment by mrogman** [comment]
do we have to route / to a template? On the other hand, we could always just take the plunge and ditch scrollify altogether... :smirk:

**Comment by afuhrtrumpet** [comment]
We do, otherwise the admin route doesn't function (because it renders the index.html stuff for every route). If we want to ditch scrollify I'm thinking http://benoit.pointet.info/stuff/jquery-scrollsnap-plugin/, the animation feels much better than scrollify as well.

**Comment by Finnbar22** [comment]
Intruding in here a little bit. If I remember correctly from our last meeting, I think we did say we would probably take out scrollify. If you guys want to on your machines J3RN mentioned to 
- Remove `js/jquery.scrollify.min.js`
- Remove everything in `js/main.js` that says anything about `scrollify`. Which is just about everything other than the second line that sets the height of each `.section`.

I think there also may have been one more thing necessary but my mind is falling short right now.

**Comment by mrogman** [comment]
Scrollsnap looks good in my opinion. I think it'd be worth our time to give it a try and see how it looks considering that we now have two major issues with scrollify (animation delay and meteor-admin compatability) that may or may not be fixed easily.

**Comment by mrogman** [comment]
For the time being, I fixed the problem with scrollify not working when the page is loaded. I changed it so that the scrollify javascript is not executed until after the main template is rendered

**Comment by afuhrtrumpet** [comment]
Cool, good work there.

**Comment by mrogman** [comment]
guess that one was actually pretty easy to fix lol. hacking on the animation code still might suck though. my stance on a new plugin remains

**Pull request merged**
